spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      label: master
      uri: http://localhost:8888
      name: spring-cloud-config
      profile: dev
      server:
        git:
          uri: https://github.com/q1226085152/spring-cloud
          username:
          password:
          search-paths: spring-cloud-config/respo


server:
  port: 8888
