version: "3.7"
services:
  spring-cloud-admin:
    image: openjdk:8-jdk
    container_name: spring-cloud-admin
    working_dir: /opt/app
    volumes:
      - ../app:/opt/app
      - /etc/localtime:/etc/localtime
    command:
      - java
      - -jar
      - --spring.profiles.active=
      - spring-cloud-admin-1.0.0.jar