spring:
  application:
    name: spring-cloud-zipkin
  boot:
    admin:
      client:
        url: ${APP_BOOT_ADMIN_CLIENT_URL:http://localhost:8084}


eureka:
  client:
    serviceUrl:
      defaultZone: ${APP_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: {"health","info"}
