spring:
  application:
    name: spring-cloud-eureka
  zipkin:
    base-url: ${APP_ZIPKIN_BASE_URL:http://localhost:9411}
  boot:
    admin:
      client:
        url: ${APP_BOOT_ADMIN_CLIENT_URL:http://localhost:8084}
server:
  port: 8761

eureka:
  client:
    serviceUrl:
      defaultZone: ${APP_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: {"health","info"}
