spring:
  application:
    name: spring-cloud-zuul
  zipkin:
    base-url: ${APP_ZIPKIN_BASE_URL:http://localhost:9411}
  boot:
    admin:
      client:
        url: ${APP_BOOT_ADMIN_CLIENT_URL:http://localhost:8084}
server:
  port: 8768

eureka:
  client:
    serviceUrl:
      defaultZone: ${APP_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: spring-cloud-web-admin-feign
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: {"health","info"}
