spring:
  application:
    name: spring-cloud-admin
  zipkin:
    base-url: ${APP_ZIPKIN_BASE_URL:http://localhost:9411}


eureka:
  client:
    serviceUrl:
      defaultZone: ${APP_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: {"health","info"}
